import type { NarrativeResult } from "@/types";

/**
 * Parses and validates the raw LLM text response into a NarrativeResult.
 *
 * Scope is deliberately narrow: only validates the two keys Granite is asked
 * to produce (summary and reportedVsReal). topRisks and topDecision are
 * never generated by the LLM and are not validated here.
 *
 * On missing keys: warns and substitutes an empty string rather than throwing,
 * so a partially-formed LLM response still produces a usable brief.
 */
export function parseNarrativeResponse(
  raw: string,
  source: NarrativeResult["source"]
): NarrativeResult {
  // Extract JSON from the raw text — LLMs sometimes wrap it in markdown fences
  // or add leading/trailing prose.
  let jsonString = raw.trim();

  // Strip markdown code fences if present (```json ... ``` or ``` ... ```)
  const fenceMatch = jsonString.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenceMatch) {
    jsonString = fenceMatch[1].trim();
  }

  // Find the first { ... } block if there's surrounding prose
  const braceMatch = jsonString.match(/\{[\s\S]*\}/);
  if (braceMatch) {
    jsonString = braceMatch[0];
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonString);
  } catch {
    console.warn(
      `[briefFormatter] Could not parse LLM response as JSON (source: ${source}). ` +
        `Raw text (first 200 chars): ${raw.slice(0, 200)}`
    );
    // Return empty strings rather than crashing — the rule-based fields still work
    return { summary: "", reportedVsReal: "", source };
  }

  if (typeof parsed !== "object" || parsed === null) {
    console.warn(
      `[briefFormatter] Parsed JSON is not an object (source: ${source}).`
    );
    return { summary: "", reportedVsReal: "", source };
  }

  const obj = parsed as Record<string, unknown>;

  // Validate and extract summary
  let summary = "";
  if (typeof obj.summary === "string" && obj.summary.trim().length > 0) {
    summary = obj.summary.trim();
  } else {
    console.warn(
      `[briefFormatter] LLM response missing or empty "summary" field (source: ${source}).`
    );
  }

  // Validate and extract reportedVsReal
  let reportedVsReal = "";
  if (
    typeof obj.reportedVsReal === "string" &&
    obj.reportedVsReal.trim().length > 0
  ) {
    reportedVsReal = obj.reportedVsReal.trim();
  } else {
    console.warn(
      `[briefFormatter] LLM response missing or empty "reportedVsReal" field (source: ${source}).`
    );
  }

  // source is set by the call site — never inferred here
  return { summary, reportedVsReal, source };
}
